# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 7, 49, 54, 491887, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
